# Generated by Django 5.0.7 on 2024-08-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Biz haqimizda')),
                ('text', models.TextField(default='Uzoq yillik tajrba')),
                ('image', models.ImageField(upload_to='about_us_image/')),
            ],
        ),
    ]
