# Generated by Django 5.0.7 on 2024-08-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
